### PR TITLE
image texture alignment + menu sample

### PR DESCRIPTION
**Pull request by Biorn1950**

### CODE REVIEW

**Comment by Biorn1950** [comment]
like:
`orbis2dAlignImageX()
`
?

**Comment by masterzorag** [comment]
I propose **orbis2dGetTextureXAlign()**
Can be handy, also we already adopt the same concept to position some text lines

**Comment by psxdev** [comment]
Yes better.

I see also a rename to a file in font type, it can broke other samples please fix that with other name, perhaps cuatom font must be in user app and not in library

**Comment by Biorn1950** [comment]
right, I'll close this pull request and make a new branch who just patch orbis2dGetTextureXAlign() (and maybe for Y align too?) and one to add sample and custom font inside. Sorry I am not used to the pull request system.

**Pull request closed without merging**
